### ISSUE TITLE
Archive page

### ISSUE THREAD

**Issue by rthijssen** [kwight/debut#25]
Hey mate,

Great theme you're having here. Really enjoying it. Just one issue, and it is very possible I'm just missing something. But I can't get a 'Archive' page to show.

Any suggestions?

Cheers.

**Comment by kwight** [comment]
Hi,

Not sure I understand – your categories and tags don't show on the front end? There are no issues I can tell at the moment; can you give more details and a site to check out?

**Comment by rthijssen** [comment]
Hi kwight,

Last night I had a closer look at the Archive page and your theme and I think I understand what is going on. The archive page works fine when used via the drop down (widget). I think I was looking for the ability to add a page that will list all the posts present on the blog. Does your theme provide this?

Cheers.

**Comment by kwight** [comment]
Out of the box, that's what the front page is (WordPress, not theme specific). You can also create a page, and then set that page as the Post Page at Settings >Reading > Front page displays (again, the is WordPress functionality, not theme specific). More info here: http://codex.wordpress.org/Settings_Reading_Screen
